### ISSUE TITLE
multikey with a value tuple

### ISSUE THREAD

**Issue by gitdhar** [siffiejoe/lua-multikey#1]
Hi,
Is it possible to have a table where the key is also a tuple.
Ex: mk.get(t, {a,b,c}) returns value {d,e,f}

**Comment by siffiejoe** [comment]
The easiest solution would be to use `table.unpack` on your key tuple. I'd probably implement an extra module for this kind of stuff, though, which does interning similar to Lua strings on tuple creation. You would need a weak-valued multikey table that acts like a cache (you'd have to protect `t[ KEY ]` from being gc'd by storing an extra reference somewhere). And your tuples would need a gc metamethod to clean up the index data. This way tuples could be used as keys in ordinary tables.

**Comment by siffiejoe** [comment]
I've added a sample implementation of what I had in mind. It definitely won't work in Lua 5.1 (some internal data structures won't be cleaned up), and my testing was minimal ...

**Comment by tst2005** [comment]
I don't if it is related but @siffiejoe you spoke about lua5.1.

`multikey` set meta handler for ipairs.

The `ipairs` behavior is different between lua 5.1, 5.2 and 5.3.

The Lua 5.1 one does not use the custom meta `__ipairs` handler.

I don't know what is your minimal test use it but it can be an ipairs issue.

My little work done about pairs/next/ipairs is [here](https://github.com/tst2005/lua-behaviors/tree/master/ipairs_pairs_next)
If you want an lua 5.2 ipairs on lua 5.1 you can try my [ipairs52](https://github.com/tst2005/lua-behaviors/blob/master/ipairs_pairs_next/ipairs5x.lua#L59)

Regards,

**Comment by siffiejoe** [comment]
I meant the missing __gc metamethod for tables, but I think I fixed that with newproxy. ipairs isn't used in the tuple module, and I consider the __ipairs metamethod optional anyway.

**Comment by siffiejoe** [comment]
Can this be closed, or are there any open questions?
